# Generated by Django 5.0.7 on 2024-07-17 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('chat_name', models.CharField(max_length=255)),
                ('user_pic', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'avito_chats',
            },
        ),
        migrations.CreateModel(
            name='AvitoIgnoredChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'avito_ignored_chats',
            },
        ),
        migrations.CreateModel(
            name='AvitoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'avito_messages',
            },
        ),
        migrations.CreateModel(
            name='AvitoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255, unique=True)),
                ('assistant_key', models.CharField(max_length=255)),
                ('triggers', models.TextField(blank=True, null=True)),
                ('check_phone', models.BooleanField(default=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('tg_manager', models.CharField(max_length=255)),
                ('wait_time', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'avito_accounts',
            },
        ),
    ]
