# Generated by Django 5.0.7 on 2024-07-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='should_ping_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='time_to_shutdown',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='time_to_trigger',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
