# Generated by Django 5.0.7 on 2024-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_avitoaccount_should_ping_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitochat',
            name='tokens',
            field=models.TextField(default=100000),
        ),
    ]
