# Generated by Django 5.0.7 on 2024-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_avitochat_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoaccount',
            name='time_to_shutdown',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='time_to_trigger',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
