# Generated by Django 5.0.7 on 2024-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_avitoaccount_bot_interval_avitoaccount_bot_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitoaccount',
            old_name='should_ping_manager',
            new_name='should_ping_manager_after_shutdown',
        ),
        migrations.RenameField(
            model_name='avitochat',
            old_name='status',
            new_name='can_send_reminder',
        ),
        migrations.RemoveField(
            model_name='avitoaccount',
            name='manager_interval',
        ),
        migrations.AddField(
            model_name='avitochat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
